include:
  - compose.image.yaml
services:
  x11-audio-demo:
    image: ${APP_IMAGE}:latest
    container_name: ${APP_IMAGE}_container
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/${PUID:-1000}/pulse/native
    devices:
      - /dev/snd
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/${PUID:-1000}/pulse:/run/user/${PUID:-1000}/pulse
    profiles:
      - production
