services:

  project.local:
    image: ${PROJECT_IMAGE_NAME:?err}.local
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_SRC: ${PROJECT_IMAGE_NAME:?err}
        USERNAME: ${USERNAME:?err}
        USER_UID: ${USER_UID:?err}
        USER_GID: ${USER_GID:?err}
        GROUPS: ${GROUPS:?err}
        GROUP_IDS: ${GROUP_IDS:?err}