include:
  - compose.image.yaml
services:
  worker:
    image: ${WORKER_IMAGE}:latest
    container_name: ${WORKER_IMAGE}_container
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    profiles:
      - production
    volumes:
      - volume_data:/data

volumes:
  volume_data: