services:

  base:
    image: ${BASE_IMAGE_NAME:?err}
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        DOCKER_SRC: ${BASE_IMAGE_SRC:?err}

  project.base:
    image: ${PROJECT_IMAGE_NAME:?err}
    build:
      context: .
      dockerfile: Dockerfile.project
      args:
        DOCKER_SRC: ${BASE_IMAGE_NAME:?err}
    depends_on:
      - base
