name: Test Docker Installation

on:
  release:
    types:
      - created

jobs:

  test-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Dockyman template test
      run: |
        echo "y" | make -C template/.dockyman install-docker
        echo "y" | make -C template/.dockyman install-docker-compose
        make -C template/.dockyman

    - name: Test Docker
      run: |
        docker --version
        docker-compose --version
