name: Build and Push Docker Image
on:
  release:
    types:
      - created

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  TEMPLATE_TOKEN: ${{ secrets.TEMPLATE_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
                submodules: recursive

      - name: Extract version from .env file
        id: extract-version
        run: |
          DOCKYMAN_VER=$(grep -oP '^DOCKYMAN_VER=\K.*' .devcontainer/.env)
          echo "::set-output name=version::$DOCKYMAN_VER"

      - name: Authenticate to template submodule
        run: |
          cd template
          git config http.https://github.com/s4hri/dockyman-template.extraheader "Authorization: Bearer $TEMPLATE_TOKEN"
          cd ..

      - name: Check submodule status
        run: |
          cd template
          git status
          cd ..

      - name: Commit and push submodule changes
        run: |
          cd template
          git add .
          git commit -m "Update submodule"
          git push
          cd ..

      - name: Build and push Docker image
        env:
          PROJECT_VERSION: ${{ steps.extract-version.outputs.version }}
        run: |
          echo "Building Docker image..."
          docker build -t $DOCKER_USERNAME/dockyman:latest -t $DOCKER_USERNAME/dockyman:${{ steps.extract-version.outputs.version }} .devcontainer/
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          echo "Pushing Docker image..."
          docker push $DOCKER_USERNAME/dockyman:latest
          docker push $DOCKER_USERNAME/dockyman:${{ steps.extract-version.outputs.version }}
