name: Build and Push Docker Image
on:
  release:
    types:
      - created

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          repository: s4hri/dockyman-template
          token: ${{ secrets.GIT_TOKEN }}
          path: template

      - name: Extract version from .env file
        id: extract-version
        run: |
          echo "VERSION=$(grep -oP '^DOCKYMAN_VER=\K.*' .devcontainer/.env)" >> $GITHUB_ENV

      - name: Build and push Docker image
        env:
          PROJECT_VERSION: ${{ steps.extract-version.outputs.version }}
          DOCKER_IMAGE_TAG: ${{ secrets.DOCKER_USERNAME }}/dockyman
        run: |
          echo "Building Docker image..."
          docker build -t $DOCKER_IMAGE_TAG:latest -t $DOCKER_IMAGE_TAG:${{ steps.extract-version.outputs.version }} --file .devcontainer/ ../
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          echo "Pushing Docker image..."
          docker push $DOCKER_IMAGE_TAG:latest
          docker push $DOCKER_IMAGE_TAG:${{ steps.extract-version.outputs.version }}